# Docs: https://pre-commit.com/
#
# Quickstart:
# $ pip3 install pre-commit
# $ pre-commit install
# $ pre-commit autoupdate
# $ pre-commit run -a
# < edit json, yaml, (ba)sh, add trailing whitespace etc >
# $ git add .
# $ git commit
#
# If the pre-commit hook is broken, it can be removed by deleting the file
# at .git/hooks/pre-commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
