# https://github.com/Azure/bicep-deploy/blob/main/examples/STACKS.md

name: Azure Stacks (Create)

on:
  workflow_dispatch:
  push:
    branches:
      - azure

permissions:
  contents: read
  id-token: write

jobs:
  deployment:
    name: "Azure infra deployment Stack"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create
        uses: azure/bicep-deploy@v2
        with:
          type: deploymentStack
          operation: create
          name: Development
          location: northeurope
          scope: subscription
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template-file: ./main.bicep
          #parameters: '{"name": "Development", "tags": { "environment": "development" }}'
          parameters-file: ./azuredeploy.parameters.json
          action-on-unmanage-resources: delete
          action-on-unmanage-resourcegroups: delete
          deny-settings-mode: denyWriteAndDelete
          description: "Development Environment"
