# https://raw.githubusercontent.com/Azure/actions-workflow-samples/refs/heads/master/FunctionApp/linux-dotnet-functionapp-on-azure.yml
name: Deploy DotNet project to Azure Function App

on:
  workflow_dispatch:
  push:
    branches:
      - azure

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
# https://azure.github.io/actions/
#
# 1. Set up the following secrets in your repository:
#   AZURE_FUNCTIONAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:

env:
  AZURE_FUNCTIONAPP_NAME: '${{ github.event.repository.name }}'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8.0.x'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.TARGET_ENV || 'dev' }}

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        echo "AZURE_FUNCTIONAPP_PACKAGE=${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output" >> $GITHUB_ENV
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
